---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  labels:
    app: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
    spec:
      containers:
        - name: distributor
          image: selenium/distributor:latest
          ports:
            - containerPort: 5553
          env:
            - name: EVENTS_BIND
              value: "false"
            - name: EVENTS_PUBLISH
              value: "tcp://event-bus:4442"
            - name: EVENTS_SUBSCRIBE
              value: "tcp://event-bus:4443"
            - name: SESSIONS_HOSTNAME
              value: "session-map"
            - name: SESSIONS_PORT
              value: "5556"
            - name: SESSIONQUEUE_HOSTNAME
              value: "session-queue"
            - name: SESSIONQUEUE_PORT
              value: "5559"
          resources:
            limits:
              memory: "512Mi"
              cpu: ".5"
          readinessProbe:
            httpGet:
              port: 5553
              path: "/readyz"
            initialDelaySeconds: 5
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: distributor
  labels:
    run: distributor
spec:
  type: NodePort
  selector:
    app: distributor
  ports:
    - port: 5553
      targetPort: 5553
      protocol: TCP
      name: web
