name: Build selenium-manager

on: workflow_dispatch

jobs:
  win32:
    name: "[Windows x32] Build selenium-manager"
    runs-on: windows-latest
    env:
      RUSTFLAGS: '-Ctarget-feature=+crt-static'
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v4
      - name: "Update Rust"
        run: |
          rustup update
          rustup toolchain install stable-i686-pc-windows-msvc
          rustup default stable-i686-pc-windows-msvc
          rustc -vV
      - name: "Build release"
        run: |
          cd rust
          cargo build --release
      - name: "Upload binary"
        uses: actions/upload-artifact@v3
        with:
          name: selenium-manager_windows-x32
          path: rust/target/release/selenium-manager.exe
          retention-days: 6

  linux64:
    name: "[Linux x64] Build selenium-manager"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v4
      - name: "Update Rust"
        run: |
          rustup update
          rustc -vV
      - name: "Install cross"
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          cross -V
      - name: "Build release"
        run: |
          cd rust
          cross build --target x86_64-unknown-linux-musl --release
      - name: "Tar binary (to keep executable permission)"
        run: |
          cd rust/target/x86_64-unknown-linux-musl/release
          tar -cvf ../../../../selenium-manager.tar selenium-manager
      - name: "Upload binary"
        uses: actions/upload-artifact@v3
        with:
          name: selenium-manager_linux-x64
          path: selenium-manager.tar
          retention-days: 6

  macos64:
    name: "[macOS x64/arm64] Build selenium-manager"
    runs-on: macos-latest
    env:
      RUSTFLAGS: '-Ctarget-feature=+crt-static'
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v4
      - name: "Update Rust"
        run: |
          rustup update
          rustup target add aarch64-apple-darwin
          rustc -vV
      - name: "Build x64"
        run: |
          cd rust
          cargo build --release --target x86_64-apple-darwin
      - name: "Build arm64"
        run: |
          cd rust
          cargo build --release --target aarch64-apple-darwin
      - name: "Build universal"
        run: |
          cd rust
          lipo -create \
            -output target/selenium-manager \
            target/aarch64-apple-darwin/release/selenium-manager \
            target/x86_64-apple-darwin/release/selenium-manager
      - name: "Tar binary (to keep executable permission)"
        run: |
          cd rust/target
          tar -cvf ../../selenium-manager.tar selenium-manager
      - name: "Upload binary"
        uses: actions/upload-artifact@v3
        with:
          name: selenium-manager_macos-universal
          path: selenium-manager.tar
          retention-days: 6
