name: CI - RBE

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rbe-small-tests:
    name: RBE - Small Tests
    uses: ./.github/workflows/bazel.yml
    with:
      name: Cache
      cache-key: java
      run: bazel test --config=remote-ci --test_size_filters=small --keep_going //java/...
