name: Should workflow run?

on:
  workflow_call:
    inputs:
      commit-range:
        description: Commits considered to determine bazel targets
        required: false
        type: string
        default: HEAD^..HEAD
      bazel-target-prefix:
        description: Bazel target prefix used to determine if the code path will be used
        required: true
        type: string

    outputs:
      result:
        description: "Boolean to be used in the job to decide if the job runs or not"
        value: ${{ jobs.check_workflow_run.outputs.result }}

jobs:
  check_workflow_run:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check-bazel-target-prefix.outputs.run-workflow }}
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: Setup Bazel
        uses: p0deje/setup-bazel@0.2.0
        with:
          bazelisk-cache: true
          external-cache: |
            name: should-workflow-run
            manifest:
              crates: rust/Cargo.Bazel.lock
              npm: package-lock.json
              pypi__pip: py/requirements_lock.txt
              rules_ruby_dist: rb/ruby_version.bzl
          repository-cache: true
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Check bazel target prefix
        id: check-bazel-target-prefix
        run: |
          ./scripts/github-actions/should-workflow-run.sh
        shell: bash
        env:
          BAZEL_TARGET_PREFIX: ${{ inputs.bazel-target-prefix }}
